################
# Cert-manager #
################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: services
spec:
  project: infrastructure
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/cert-manager
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
#########
# Gists #
#########
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gists
  namespace: services
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Project for the gist application
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gists
  namespace: services
spec:
  project: gists
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/gists/gists
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - tag.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-gists
  namespace: services
spec:
  project: gists
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/gists/database
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-gists
  namespace: services
spec:
  project: gists
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/gists/gists-front
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - tag.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sealci
  namespace: services
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Project for the sealci application
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controller-sealci
  namespace: services
spec:
  project: sealci
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/sealci/controller
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-sealci
  namespace: services
spec:
  project: sealci
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/sealci/database
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scheduler-sealci
  namespace: services
spec:
  project: sealci
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/sealci/scheduler
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: courtcircuits-portfolio
  namespace: services
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Project for my personal portfolio
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: courtcircuits-portfolio
  namespace: services
spec:
  project: courtcircuits-portfolio
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/courtcircuits/portfolio
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - tag.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: airflow-poc
  namespace: services
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Project for an airflow deployment
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-poc
  namespace: services
spec:
  project: airflow-poc
  source:
    repoURL: "https://github.com/Courtcircuits/cluster"
    path: projects/airflow
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: airswagg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
