#############
# Ratathune #
#############
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ratathune
  namespace: services
spec:
  project: default
  source:
    repoURL: 'https://github.com/Courtcircuits/cluster'
    path: projects/ratathune/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
################
# Cert-manager #
################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: services
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/Courtcircuits/cluster'
    path: projects/cert-manager
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
#############
# Ratathune #
#############
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hackthecrous
  namespace: services
spec:
  project: default
  source:
    repoURL: 'https://github.com/Courtcircuits/cluster'
    path: projects/hackthecrous
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true