apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: services
spec:
  project: applications
  source:
    repoURL: 'https://github.com/Courtcircuits/cluster'
    path: projects
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
