apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: services
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Project containing all applications used by courtcircuits' cluster
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - '*'
