apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ratathune
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Courtcircuits/cluster'
    path: projects/ratathune/*.yaml
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true