executor: "KubernetesExecutor"
createUserJob:
  enabled: true
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  enabled: true
  useHelmHooks: false
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync
extraSecrets:
  "{{ .Release.Name }}-example":
    useHelmHooks: false
    data: |
      AIRFLOW_VAR_HELLO_MESSAGE: "Hi!"

extraConfigMaps:
  "{{ .Release.Name }}-example":
    useHelmHooks: false
    data: |
      AIRFLOW_VAR_HELLO_MESSAGE: "Hi!"
