airflow:
  executor: "KubernetesExecutor"
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      "argocd.argoproj.io/hook": Sync
  postgresql: # by default postgres shipped by the chart
    enabled: false
  data:
    metadataConnection:
      user: postgres
      pass: postgres
      protocol: postgresql
      host: airflow-poc-postgres-ha-postgresql.airswagg.svc.cluster.local
      port: 5432
      db: "airflow"
postgres-ha: # HA postgres
  postgresPassword: "postgres"
  database: "airflow"
  repmgrUsername: "repmgr"
  repmgrPassword: "repmgr_password"
