airflow:
  executor: "KubernetesExecutor"
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      "argocd.argoproj.io/hook": Sync
  postgresql: # by default postgres shipped by the chart
    enabled: false

postgresql: # HA postgres
  postgresql:
    postgresPassword: "postgres"
