apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ratathune-frontend
  namespace: argocd
spec:
  project: ratathune
  source:
    repoURL: 'https://github.com/Courtcircuits/Rathatune-client'
    path: deployment/front
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ratathune
  syncPolicy:
    automated:
      prune: true
      selfHeal: true