apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratathune-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/redirection-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  labels:
    name: ratathune-ingress
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - api.{{ .Values.ratathune.host }}
    - {{ .Values.ratathune.host }}
    secretName: "ratathune-tls-ca-part-en-prod"
  rules:
  - host: api.{{ .Values.ratathune.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ratathune-server
            port: 
              number: 80
  - host: {{ .Values.ratathune.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ratathune-front
            port: 
              number: 80
  - host: avatars.{{ .Values.ratathune.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port:
              number: 9000
