
apiVersion: v1
kind: Service
metadata:
  name: "gists-front"
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.gists.host }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Release.Name }}-deployment
  selector:
    app: {{ .Release.Name }}-deployment
