apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scheduler-sealci-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/redirection-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  labels:
    name: scheduler-sealci-ingress
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.scheduler.host }}
      secretName: "scheduler-sealci-tls-ca-part-en-prod"
  rules:
    - host: {{ .Values.scheduler.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "scheduler-sealci"
                port:
                  number: {{ .Values.service.externalPort }}
