rootDomain: courtcircuits.xyz
clusterIssuer: ca-issuer
argocdServiceName: services-argocd-server

harbor:
  externalURL: https://harbor.courtcircuits.xyz
  exposureType: "ingress"
  ingress:
    core:
      hostname: "harbor.courtcircuits.xyz"
  registry:
    relativeurls: true

argocd:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  repoServer:
    resources:
      requests:controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true