image: "milou666/gists-api"
tag: "latest"
replicaCount: 1
service:
  externalPort: 80
  internalPort: 4000
gists:
  host: "api-gists.courtcircuits.xyz"
  ingress:
    enabled: true
postgres:
  secret: "database-gists-postgresql"

jobs:
  - name: "migrate"
    command: ["./main", "migrate"]
