apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ .Release.Name }}-deployment
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        env:
        - name: PORT
          value: {{ .Values.service.internalPort | quote }}
        - name: PG_USER
          value: "postgres"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.secret }}
              key: postgres-password
        - name: PG_PORT
          value: "5432"
        - name: PG_HOST
          value: "database-gists-postgresql.gists.svc.cluster.local"
        - name: PG_DATABASE
          value: "gists"
        - name: FRONTEND_URL
          value: "https://gists.app"
        - name: ENV
          value: "production"
        {{- $values := .Values -}}
        {{- range $.Values.gists.secrets}}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: "gists-secrets-deployment"
              key: {{ .name }}
        {{- end}}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort | int }}
