# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gists-ingress
#   namespace: {{ .Release.Namespace }}
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-production
#     traefik.ingress.kubernetes.io/redirection-entry-point: https
#     traefik.ingress.kubernetes.io/redirect-permanent: "true"
#     external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
#     traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace}}-rate-limit@kubernetescrd
#   labels:
#     name: gists-ingress
# spec:
#   ingressClassName: traefik
#   tls:
#     - hosts:
#         - {{ .Values.gists.host }}
#       secretName: "gists-tls-ca-part-en-prod"
#   rules:
#     - host: {{ .Values.gists.host }}
#       http:
#         paths:
#           - pathType: Prefix
#             path: "/"
#             backend:
#               service:
#                 name: gists
#                 port:
#                   number: {{ .Values.service.externalPort }}
