apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: raw-gists-middleware
spec:
  redirectRegex:
    regex: http://raw\.gists\.app/(.+)$
    replacement: http://api.gists.app/gists/$1
    permanent: true
