apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: raw-gists-middleware
  namespace: {{ .Release.Namespace }}
spec:
  replacePathRegex:
    regex: ^/([a-zA-Z0-9]+)$
    replacement: /gists/$1\?raw=true
