apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-dataviz-ingress
  namespace: {{ .Release.Namespace}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/redirection-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  labels:
    name: ratathune-ingress
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.spotifydataviz.host }}
    secretName: "spotify-dataviz-tls-ca-part-en-prod"
  rules:
  - host: {{ .Values.spotifydataviz.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: spotify-dataviz
            port: 
              number: {{ .Values.service.externalPort }}
