apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotify-dataviz.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spotify-dataviz.selectorLabels" . | nindent 4 }}
