name: Lint Kubernetes files
run-name: ${{ github.actor }} is making sure that the manifest are bullet proof 🚀
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'services/**'
      - 'projects/**'
      - 'app-of-apps/**'
      - '*.yaml'
      - '*.yml'

jobs:
  kube-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          config: .kube-linter.yaml
          directory: "."
          output-file: kube-linter.sarif
          fail-on-invalid-resource: false
      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kube-linter.sarif
          wait-for-processing: true

