name: Lint Kubernetes files
on:
  pull_request:
    paths:
      - 'services/**'
      - 'projects/**'
      - 'app-of-apps/**'
      - '*.yaml'
      - '*.yml'
  push:
    branches:
      - main

jobs:
  kube-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kube-linter
        uses: docker://docker.io/stackrox/kube-linter:latest
        with:
          config: .kube-linter.yaml
          directory: "."
          output-file: kube-linter.sarif

      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kube-linter.sarif
          wait-for-processing: true

